services:
  nextjs:
    build:
      context: ./admin-panel  # Change context to admin-panel directory
      dockerfile: Dockerfile   # Specify Dockerfile location
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/testdb?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm start"]

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
