version: '3.8'
services: 
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - DATABASE_URL="postgresql://postgres:password@localhost:5432/testdb"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    posts:
      - "5432:5432"
  
  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - nextjs

volumes:
  postgres_data: