version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"  # Changed to avoid local port conflict
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile  # Explicitly specify Dockerfile
    container_name: nextjs-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/testdb?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge