import React from 'react'
import Title from './title'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};


const Dashboard = () => {
  return (
    <div> 
      <Title/>
    </div>
  )
}

export default Dashboard