name: Deploy to Linode (VPS)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
    
    - name: Deploy to Linode
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} <<EOF
          cd /opt/app/admin-panel
          git pull origin main
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npm run build
          pm2 restart nextjs-app
        EOF