name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Application via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 172.232.107.48
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to project directory
          cd /opt/majesticbridal

          # Pull latest changes from GitHub
          git reset --hard
          git pull origin main

          # Stop existing containers
          docker-compose down

          # Start updated containers
          docker-compose up -d --build

          # Save PM2 process for automatic restarts
          pm2 restart majestic-bridal || pm2 start "docker-compose up -d" --name majestic-bridal
          pm2 save
